apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudstack
  template:
    metadata:
      labels:
        app: cloudstack
    spec:
      containers:
      - name: cloudstack-simulator
        image: rakgenius/cloudstack-simulator
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
