apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: cloudstack
build:
  artifacts:
  - image: cloudstack-simulator
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yml
    - ingress.yml
    - service.yml
